Rename pip() resp columns
PIP-Technical-Team/pipapi pull request #207
Opened 2022-02-11 12:55 UTC by Aeilert

First draft

2022-02-21 14:39 UTC, tonyfujs requested changes
Hey @Aeilert,

I've made some code update to fix the empty response and some unit tests.

Currently, some `ui_functions()` are failing because of the column name inconsistency. They are also pulling data from lkup tables (which have not been renamed...)

One potential solution to move forward with the renaming, and still avoid making the corresponding changes at the pipeline level, would be to rename all lookup tables in the `create_lkup()` function. What do you think?

2022-02-22 07:03 UTC, Aeilert commented
Thanks @tonyfujs, 

I agree that renaming in columns in the `create_lkup()` function is a good idea. This won't cover all cases though since some AUX datasets are read directly from disk.  But still something I think we could forward with

2022-02-23 10:31 UTC, tonyfujs approved these changes
Looks good @Aeilert Just made a small update to a unit test that was failing. (related to separate PR on increasing max PL)

2022-07-25 15:36 UTC, randrescastaneda commented
Task linked: [CU-2me746v Rename pip() resp columns](https://app.clickup.com/t/2me746v)

2025-07-21 22:12 UTC, closed without merging